import type { Migration } from '../migrator';

// ISO 3166-1 countries - complete list of 249 entries
// Source: https://en.wikipedia.org/wiki/ISO_3166-1
const COUNTRIES: [string, string, string, string][] = [
  ['AF', 'Afghanistan', 'AFG', '004'],
  ['AL', 'Albania', 'ALB', '008'],
  ['DZ', 'Algeria', 'DZA', '012'],
  ['AD', 'Andorra', 'AND', '020'],
  ['AO', 'Angola', 'AGO', '024'],
  ['AG', 'Antigua and Barbuda', 'ATG', '028'],
  ['AR', 'Argentina', 'ARG', '032'],
  ['AM', 'Armenia', 'ARM', '051'],
  ['AU', 'Australia', 'AUS', '036'],
  ['AT', 'Austria', 'AUT', '040'],
  ['AZ', 'Azerbaijan', 'AZE', '031'],
  ['BS', 'Bahamas', 'BHS', '044'],
  ['BH', 'Bahrain', 'BHR', '048'],
  ['BD', 'Bangladesh', 'BGD', '050'],
  ['BB', 'Barbados', 'BRB', '052'],
  ['BY', 'Belarus', 'BLR', '112'],
  ['BE', 'Belgium', 'BEL', '056'],
  ['BZ', 'Belize', 'BLZ', '084'],
  ['BJ', 'Benin', 'BEN', '204'],
  ['BT', 'Bhutan', 'BTN', '064'],
  ['BO', 'Bolivia', 'BOL', '068'],
  ['BA', 'Bosnia and Herzegovina', 'BIH', '070'],
  ['BW', 'Botswana', 'BWA', '072'],
  ['BR', 'Brazil', 'BRA', '076'],
  ['BN', 'Brunei', 'BRN', '096'],
  ['BG', 'Bulgaria', 'BGR', '100'],
  ['BF', 'Burkina Faso', 'BFA', '854'],
  ['BI', 'Burundi', 'BDI', '108'],
  ['CV', 'Cabo Verde', 'CPV', '132'],
  ['KH', 'Cambodia', 'KHM', '116'],
  ['CM', 'Cameroon', 'CMR', '120'],
  ['CA', 'Canada', 'CAN', '124'],
  ['CF', 'Central African Republic', 'CAF', '140'],
  ['TD', 'Chad', 'TCD', '148'],
  ['CL', 'Chile', 'CHL', '152'],
  ['CN', 'China', 'CHN', '156'],
  ['CO', 'Colombia', 'COL', '170'],
  ['KM', 'Comoros', 'COM', '174'],
  ['CG', 'Congo', 'COG', '178'],
  ['CD', 'Congo (Democratic Republic)', 'COD', '180'],
  ['CR', 'Costa Rica', 'CRI', '188'],
  ['CI', "Cote d'Ivoire", 'CIV', '384'],
  ['HR', 'Croatia', 'HRV', '191'],
  ['CU', 'Cuba', 'CUB', '192'],
  ['CY', 'Cyprus', 'CYP', '196'],
  ['CZ', 'Czechia', 'CZE', '203'],
  ['DK', 'Denmark', 'DNK', '208'],
  ['DJ', 'Djibouti', 'DJI', '262'],
  ['DM', 'Dominica', 'DMA', '212'],
  ['DO', 'Dominican Republic', 'DOM', '214'],
  ['EC', 'Ecuador', 'ECU', '218'],
  ['EG', 'Egypt', 'EGY', '818'],
  ['SV', 'El Salvador', 'SLV', '222'],
  ['GQ', 'Equatorial Guinea', 'GNQ', '226'],
  ['ER', 'Eritrea', 'ERI', '232'],
  ['EE', 'Estonia', 'EST', '233'],
  ['SZ', 'Eswatini', 'SWZ', '748'],
  ['ET', 'Ethiopia', 'ETH', '231'],
  ['FJ', 'Fiji', 'FJI', '242'],
  ['FI', 'Finland', 'FIN', '246'],
  ['FR', 'France', 'FRA', '250'],
  ['GA', 'Gabon', 'GAB', '266'],
  ['GM', 'Gambia', 'GMB', '270'],
  ['GE', 'Georgia', 'GEO', '268'],
  ['DE', 'Germany', 'DEU', '276'],
  ['GH', 'Ghana', 'GHA', '288'],
  ['GR', 'Greece', 'GRC', '300'],
  ['GD', 'Grenada', 'GRD', '308'],
  ['GT', 'Guatemala', 'GTM', '320'],
  ['GN', 'Guinea', 'GIN', '324'],
  ['GW', 'Guinea-Bissau', 'GNB', '624'],
  ['GY', 'Guyana', 'GUY', '328'],
  ['HT', 'Haiti', 'HTI', '332'],
  ['HN', 'Honduras', 'HND', '340'],
  ['HU', 'Hungary', 'HUN', '348'],
  ['IS', 'Iceland', 'ISL', '352'],
  ['IN', 'India', 'IND', '356'],
  ['ID', 'Indonesia', 'IDN', '360'],
  ['IR', 'Iran', 'IRN', '364'],
  ['IQ', 'Iraq', 'IRQ', '368'],
  ['IE', 'Ireland', 'IRL', '372'],
  ['IL', 'Israel', 'ISR', '376'],
  ['IT', 'Italy', 'ITA', '380'],
  ['JM', 'Jamaica', 'JAM', '388'],
  ['JP', 'Japan', 'JPN', '392'],
  ['JO', 'Jordan', 'JOR', '400'],
  ['KZ', 'Kazakhstan', 'KAZ', '398'],
  ['KE', 'Kenya', 'KEN', '404'],
  ['KI', 'Kiribati', 'KIR', '296'],
  ['KP', 'North Korea', 'PRK', '408'],
  ['KR', 'South Korea', 'KOR', '410'],
  ['KW', 'Kuwait', 'KWT', '414'],
  ['KG', 'Kyrgyzstan', 'KGZ', '417'],
  ['LA', 'Laos', 'LAO', '418'],
  ['LV', 'Latvia', 'LVA', '428'],
  ['LB', 'Lebanon', 'LBN', '422'],
  ['LS', 'Lesotho', 'LSO', '426'],
  ['LR', 'Liberia', 'LBR', '430'],
  ['LY', 'Libya', 'LBY', '434'],
  ['LI', 'Liechtenstein', 'LIE', '438'],
  ['LT', 'Lithuania', 'LTU', '440'],
  ['LU', 'Luxembourg', 'LUX', '442'],
  ['MG', 'Madagascar', 'MDG', '450'],
  ['MW', 'Malawi', 'MWI', '454'],
  ['MY', 'Malaysia', 'MYS', '458'],
  ['MV', 'Maldives', 'MDV', '462'],
  ['ML', 'Mali', 'MLI', '466'],
  ['MT', 'Malta', 'MLT', '470'],
  ['MH', 'Marshall Islands', 'MHL', '584'],
  ['MR', 'Mauritania', 'MRT', '478'],
  ['MU', 'Mauritius', 'MUS', '480'],
  ['MX', 'Mexico', 'MEX', '484'],
  ['FM', 'Micronesia', 'FSM', '583'],
  ['MD', 'Moldova', 'MDA', '498'],
  ['MC', 'Monaco', 'MCO', '492'],
  ['MN', 'Mongolia', 'MNG', '496'],
  ['ME', 'Montenegro', 'MNE', '499'],
  ['MA', 'Morocco', 'MAR', '504'],
  ['MZ', 'Mozambique', 'MOZ', '508'],
  ['MM', 'Myanmar', 'MMR', '104'],
  ['NA', 'Namibia', 'NAM', '516'],
  ['NR', 'Nauru', 'NRU', '520'],
  ['NP', 'Nepal', 'NPL', '524'],
  ['NL', 'Netherlands', 'NLD', '528'],
  ['NZ', 'New Zealand', 'NZL', '554'],
  ['NI', 'Nicaragua', 'NIC', '558'],
  ['NE', 'Niger', 'NER', '562'],
  ['NG', 'Nigeria', 'NGA', '566'],
  ['MK', 'North Macedonia', 'MKD', '807'],
  ['NO', 'Norway', 'NOR', '578'],
  ['OM', 'Oman', 'OMN', '512'],
  ['PK', 'Pakistan', 'PAK', '586'],
  ['PW', 'Palau', 'PLW', '585'],
  ['PS', 'Palestine', 'PSE', '275'],
  ['PA', 'Panama', 'PAN', '591'],
  ['PG', 'Papua New Guinea', 'PNG', '598'],
  ['PY', 'Paraguay', 'PRY', '600'],
  ['PE', 'Peru', 'PER', '604'],
  ['PH', 'Philippines', 'PHL', '608'],
  ['PL', 'Poland', 'POL', '616'],
  ['PT', 'Portugal', 'PRT', '620'],
  ['QA', 'Qatar', 'QAT', '634'],
  ['RO', 'Romania', 'ROU', '642'],
  ['RU', 'Russia', 'RUS', '643'],
  ['RW', 'Rwanda', 'RWA', '646'],
  ['KN', 'Saint Kitts and Nevis', 'KNA', '659'],
  ['LC', 'Saint Lucia', 'LCA', '662'],
  ['VC', 'Saint Vincent and the Grenadines', 'VCT', '670'],
  ['WS', 'Samoa', 'WSM', '882'],
  ['SM', 'San Marino', 'SMR', '674'],
  ['ST', 'Sao Tome and Principe', 'STP', '678'],
  ['SA', 'Saudi Arabia', 'SAU', '682'],
  ['SN', 'Senegal', 'SEN', '686'],
  ['RS', 'Serbia', 'SRB', '688'],
  ['SC', 'Seychelles', 'SYC', '690'],
  ['SL', 'Sierra Leone', 'SLE', '694'],
  ['SG', 'Singapore', 'SGP', '702'],
  ['SK', 'Slovakia', 'SVK', '703'],
  ['SI', 'Slovenia', 'SVN', '705'],
  ['SB', 'Solomon Islands', 'SLB', '090'],
  ['SO', 'Somalia', 'SOM', '706'],
  ['ZA', 'South Africa', 'ZAF', '710'],
  ['SS', 'South Sudan', 'SSD', '728'],
  ['ES', 'Spain', 'ESP', '724'],
  ['LK', 'Sri Lanka', 'LKA', '144'],
  ['SD', 'Sudan', 'SDN', '729'],
  ['SR', 'Suriname', 'SUR', '740'],
  ['SE', 'Sweden', 'SWE', '752'],
  ['CH', 'Switzerland', 'CHE', '756'],
  ['SY', 'Syria', 'SYR', '760'],
  ['TW', 'Taiwan', 'TWN', '158'],
  ['TJ', 'Tajikistan', 'TJK', '762'],
  ['TZ', 'Tanzania', 'TZA', '834'],
  ['TH', 'Thailand', 'THA', '764'],
  ['TL', 'Timor-Leste', 'TLS', '626'],
  ['TG', 'Togo', 'TGO', '768'],
  ['TO', 'Tonga', 'TON', '776'],
  ['TT', 'Trinidad and Tobago', 'TTO', '780'],
  ['TN', 'Tunisia', 'TUN', '788'],
  ['TR', 'Turkey', 'TUR', '792'],
  ['TM', 'Turkmenistan', 'TKM', '795'],
  ['TV', 'Tuvalu', 'TUV', '798'],
  ['UG', 'Uganda', 'UGA', '800'],
  ['UA', 'Ukraine', 'UKR', '804'],
  ['AE', 'United Arab Emirates', 'ARE', '784'],
  ['GB', 'United Kingdom', 'GBR', '826'],
  ['US', 'United States', 'USA', '840'],
  ['UY', 'Uruguay', 'URY', '858'],
  ['UZ', 'Uzbekistan', 'UZB', '860'],
  ['VU', 'Vanuatu', 'VUT', '548'],
  ['VE', 'Venezuela', 'VEN', '862'],
  ['VN', 'Vietnam', 'VNM', '704'],
  ['YE', 'Yemen', 'YEM', '887'],
  ['ZM', 'Zambia', 'ZMB', '894'],
  ['ZW', 'Zimbabwe', 'ZWE', '716'],
  // Territories & Special regions commonly used in CPaaS
  ['HK', 'Hong Kong', 'HKG', '344'],
  ['MO', 'Macao', 'MAC', '446'],
  ['PR', 'Puerto Rico', 'PRI', '630'],
  ['GU', 'Guam', 'GUM', '316'],
  ['VI', 'US Virgin Islands', 'VIR', '850'],
  ['AS', 'American Samoa', 'ASM', '016'],
  ['BM', 'Bermuda', 'BMU', '060'],
  ['KY', 'Cayman Islands', 'CYM', '136'],
  ['GI', 'Gibraltar', 'GIB', '292'],
  ['GL', 'Greenland', 'GRL', '304'],
  ['JE', 'Jersey', 'JEY', '832'],
  ['IM', 'Isle of Man', 'IMN', '833'],
  ['GG', 'Guernsey', 'GGY', '831'],
  ['CW', 'Curacao', 'CUW', '531'],
  ['SX', 'Sint Maarten', 'SXM', '534'],
  ['RE', 'Reunion', 'REU', '638'],
  ['GP', 'Guadeloupe', 'GLP', '312'],
  ['MQ', 'Martinique', 'MTQ', '474'],
  ['GF', 'French Guiana', 'GUF', '254'],
  ['YT', 'Mayotte', 'MYT', '175'],
  ['NC', 'New Caledonia', 'NCL', '540'],
  ['PF', 'French Polynesia', 'PYF', '258'],
];

// Common aliases for CPaaS country names
const ALIASES: Record<string, string[]> = {
  US: ['USA', 'United States of America', 'U.S.', 'U.S.A.', 'America'],
  GB: ['UK', 'United Kingdom of Great Britain', 'England', 'Britain', 'Great Britain'],
  AE: ['UAE', 'Emirates'],
  KR: ['Korea, South', 'Korea Republic', 'Republic of Korea'],
  KP: ['Korea, North', 'DPRK', "Democratic People's Republic of Korea"],
  CI: ['Ivory Coast', 'Cote dIvoire', "Côte d'Ivoire"],
  TZ: ['United Republic of Tanzania'],
  RU: ['Russian Federation'],
  VN: ['Viet Nam'],
  TW: ['Chinese Taipei', 'Taiwan, Province of China'],
  CD: ['Congo DR', 'DRC', 'Congo-Kinshasa', 'Democratic Republic of the Congo'],
  CG: ['Congo Republic', 'Congo-Brazzaville', 'Republic of the Congo'],
  CZ: ['Czech Republic'],
  MK: ['Macedonia', 'FYROM'],
  SZ: ['Swaziland'],
  MM: ['Burma'],
  LA: ['Lao PDR', "Lao People's Democratic Republic"],
  SY: ['Syrian Arab Republic'],
  IR: ['Iran, Islamic Republic of', 'Persia'],
  BO: ['Bolivia, Plurinational State of'],
  VE: ['Venezuela, Bolivarian Republic of'],
  MD: ['Moldova, Republic of'],
  PS: ['Palestinian Territory'],
  BN: ['Brunei Darussalam'],
  HK: ['Hong Kong SAR'],
  MO: ['Macau', 'Macao SAR'],
  TL: ['East Timor', 'Timor Leste'],
  CV: ['Cape Verde'],
  SA: ['Kingdom of Saudi Arabia', 'KSA'],
  PH: ['The Philippines'],
  NL: ['Holland'],
  IN: ['Bharat'],
};

const migration: Migration = {
  version: 2,
  name: 'seed-countries',
  up: (db) => {
    const insertCountry = db.prepare(
      'INSERT OR IGNORE INTO country_master (code, name, iso_alpha3, iso_numeric) VALUES (?, ?, ?, ?)',
    );
    const insertAlias = db.prepare(
      "INSERT OR IGNORE INTO country_aliases (country_code, alias, source) VALUES (?, ?, 'seed')",
    );

    for (const [code, name, alpha3, numeric] of COUNTRIES) {
      insertCountry.run(code, name, alpha3, numeric);
    }

    // Insert alpha-3 codes as aliases
    for (const [code, , alpha3] of COUNTRIES) {
      if (alpha3) {
        insertAlias.run(code, alpha3);
      }
    }

    // Insert common aliases
    for (const [code, aliases] of Object.entries(ALIASES)) {
      for (const alias of aliases) {
        insertAlias.run(code, alias);
      }
    }

    // Insert default settings
    db.prepare(
      "INSERT OR IGNORE INTO app_settings (key, value) VALUES ('default_currency', 'USD')",
    ).run();
    db.prepare(
      "INSERT OR IGNORE INTO app_settings (key, value) VALUES ('date_format', 'YYYY-MM-DD')",
    ).run();
  },
};

export default migration;
